apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api
    role: feed
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api
  template:
    metadata:
      labels:
        app: udagram-api
        role: feed
        tier: backend
    spec:
      containers:
      - image: joelscander/udagram-api-feed:v8
        name: udagram-api-feed
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 0.5
        envFrom:
        - configMapRef:
            name: env-config