apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: joelscander/udagram-api-feed:latest
        name: backend-feed
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 0.5
        envFrom:
        - configMapRef:
            name: env-config