apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: joelscander/udagram-reverseproxy:v8
        name: reverseproxy
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 0.5
        envFrom:
        - configMapRef:
            name: env-config