language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed joelscander/udagram-api-feed:v2
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user joelscander/udagram-api-user:v2
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend joelscander/udagram-frontend:v2
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy joelscander/udagram-reverseproxy:v2

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joelscander/udagram-api-feed:v2
  - docker push joelscander/udagram-api-user:v2
  - docker push joelscander/udagram-frontend:v2
  - docker push joelscander/reverseproxy:v2
