apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: udagram-api
    role: user
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: udagram-api
    role: user
    tier: backend